version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: 변경하세요
      MYSQL_ROOT_PASSWORD: 변경하세요
      TZ: Asia/Seoul
    ports:

    - 3306:3306
networks:
  - backend
  redis:
    container_name: redis
    image: redis
    ports:

    - 6379:6379
networks:
  - backend
volumes:
  - ./redis.conf:/usr/local/etc/redis/redis.conf


networks:
  backend:
    driver: bridge
]